# =============================================================================
# Castração (Homologação) - Ambiente de homologação
# =============================================================================
# Server: homologacao-castracao.francodarocha.sp.gov.br
# Service: homologacao-castracao:80
# =============================================================================

server {
    include conf.d/ssl.conf;
    server_name homologacao-castracao.francodarocha.sp.gov.br;

    root /var/www/html;
    index index.html index.htm;

    include conf.d/error-pages.conf;

    location / {
        set $upstream $upstream_homologacao_castracao;
        proxy_pass http://$upstream;
        proxy_redirect off;
        include conf.d/proxy-params.conf;
    }
}
