# =============================================================================
# e-SUS (Homologação) - Ambiente de homologação
# =============================================================================
# Server: homologacao-esus.francodarocha.sp.gov.br
# Service: homologacao-esus:8080
# =============================================================================

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name homologacao-esus.francodarocha.sp.gov.br;
    return 301 https://$host$request_uri;
}

server {
    include conf.d/ssl.conf;
    server_name homologacao-esus.francodarocha.sp.gov.br;

    include conf.d/error-pages.conf;

    location / {
        set $upstream $upstream_homologacao_esus;
        proxy_pass http://$upstream;
        include conf.d/proxy-params.conf;
        proxy_buffering off;
        proxy_request_buffering off;
    }

    error_log /var/log/nginx/homologacao-esus_error.log;
    access_log /var/log/nginx/homologacao-esus_access.log;
}
