# =============================================================================
# Mapas - Sistema de mapas (PAC Web)
# =============================================================================
# Server: mapas.francodarocha.sp.gov.br
# Frontend: /home/usr001/apps/pmfrsamba/storage/pac-web
# =============================================================================

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name mapas.francodarocha.sp.gov.br;
    return 301 https://$host$request_uri;
}

server {
    include conf.d/ssl.conf;
    server_name mapas.francodarocha.sp.gov.br;

    root /home/usr001/apps/pmfrsamba/storage/pac-web;
    index index.html;

    include conf.d/error-pages.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
