# =============================================================================
# Opina - Sistema de opinião/feedback
# =============================================================================
# Server: opina.francodarocha.sp.gov.br
# Service: opina:80
# =============================================================================

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name opina.francodarocha.sp.gov.br;
    return 301 https://$host$request_uri;
}

server {
    include conf.d/ssl.conf;
    server_name opina.francodarocha.sp.gov.br;

    include conf.d/error-pages.conf;

    location / {
        set $upstream $upstream_opina;
        proxy_pass http://$upstream;
        include conf.d/proxy-params.conf;
        proxy_buffering off;
        proxy_request_buffering off;
    }

    error_log /var/log/nginx/wp_opina_error.log;
    access_log /var/log/nginx/wp_opina_access.log;
}
